plugins {
    id 'com.android.application'
}

android {
    namespace 'com.hans.android.voicebutton'
    compileSdk 34

    defaultConfig {
        applicationId 'com.hans.android.voicebutton'
        minSdk 24
        targetSdk 34
        versionCode 37
        versionName '0.37'
        buildConfigField 'String', 'VOICE_BASE_URL', '"https://jetson-fdx.jimmyandjonny.work"'
        buildConfigField 'String', 'THOR_PLAYER_BASE_URL', '"https://thor.jonnyontherun.org/speech-mobile"'
        buildConfigField 'String', 'THOR_PLAYER_TOKEN', '"-xad-MEIqaxraJg-CwU2oO3779SxDwFeNau0klgZWHfNuWg2"'
    }

    buildFeatures {
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation files('../../../modules/audio/libs/tandroidlame-1.1.aar')
    implementation project(':modules:audio')
    implementation project(':modules:network')
    implementation project(':modules:common_ui')
    implementation 'androidx.core:core:1.12.0'
    implementation 'androidx.documentfile:documentfile:1.1.0'
    implementation 'androidx.work:work-runtime:2.9.1'
    implementation 'org.videolan.android:libvlc-all:3.7.0'
    testImplementation 'junit:junit:4.13.2'
}
