plugins {
    id 'com.android.library'
}

android {
    namespace 'com.hans.android.audio'
    compileSdk 34

    defaultConfig {
        minSdk 24
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    compileOnly files('libs/tandroidlame-1.1.aar')
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.json:json:20240303'
}
