plugins {
    id 'com.android.application'
}

dependencies {
    implementation 'androidx.core:core:1.12.0'
}

android {
    namespace 'myapp.app'
    compileSdk 34
    defaultConfig {
        applicationId "myapp.app"
        minSdk 24
        targetSdk 34
    }
    buildTypes {
        release {
            minifyEnabled false
        }
    }
    packagingOptions {
        resources {
            excludes += ['META-INF/LGPL2.1']
        }
    }
}
